DELETE FROM S_ASSET WHERE ROW_ID ='2-TESTCAR1';
            DELETE FROM  S_ASSET_BU WHERE ROW_ID ='2-TESTCAR4';
            DELETE FROM  S_ASSET_ATX WHERE ROW_ID ='2-TESTCAR1';
            DELETE FROM  S_ASSET_X WHERE ROW_ID ='2-TESTCAR1';
            DELETE FROM  S_ASSET_POSTN WHERE ROW_ID ='2-TESTCAR3';
            DELETE FROM  S_AUDIT_ITEM WHERE ROW_ID ='2-TESTCAR2';
            DELETE from CX_CAR_OWN_HIST where asset_id = '2-TESTCAR1'