DELETE FROM S_ASSET WHERE ROW_ID ='6-TESTCAR1';
DELETE FROM  S_ASSET_BU WHERE ROW_ID ='6-TESTCAR4';
DELETE FROM  S_ASSET_ATX WHERE ROW_ID ='6-TESTCAR1';
DELETE FROM  S_ASSET_X WHERE ROW_ID ='6-TESTCAR1';
DELETE FROM  S_ASSET_POSTN WHERE ROW_ID ='6-TESTCAR3';
DELETE FROM  S_AUDIT_ITEM WHERE ROW_ID ='6-TESTCAR2'